# Pandas Basics Exercise
Complete the code below to declare a DataFrame with two records, each containing the fields `order_id` and `quantity` both of type  integers.  Have the first record contain an `order_id` of `1` and a `quantity` of `450`, and the second an `order_id` of `2` and a `quantity` of `700`.

Afterwards, select and display the first record.

```python
df = pd.DataFrame({
    ?: [1, 2],
    "quantity": ?
})

df.?[?]
```

## Solution

In [3]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame({
    "order_id": [1, 2],
    "quantity": [450, 700]
})

df.loc[0]

order_id      1
quantity    450
Name: 0, dtype: int64

In [8]:
df

   order_id  quantity
0         1       450
1         2       700

In [12]:
df_alt = pd.DataFrame(data=(
    [1, 450],
    [2, 700]
),
    columns=['order_id','quantity'])

df_alt

   order_id  quantity
0         1       450
1         2       700