# Data Cleaning with Pandas  
**Course Medium:**  Anaconda.com  
**Module:** Pandas Basics  
**Notebook:** 1_pandas_basics.ipynb

In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
import sys
import matplotlib

print("Python:", sys.executable)
print("Conda environment:", sys.prefix)
print("Matplotlib:", matplotlib.__file__)
print("Matplotlib version:", matplotlib.__version__)

Python: /home/bnelson_regex/miniconda3/envs/data_cleaning_pandas/bin/python3
Conda environment: /home/bnelson_regex/miniconda3/envs/data_cleaning_pandas
Matplotlib: /home/bnelson_regex/miniconda3/envs/data_cleaning_pandas/lib/python3.12/site-packages/matplotlib/__init__.py
Matplotlib version: 3.11.2

There are two main types of data structures in Pandas: the `Series` and the `DataFrame`.

## Series
A `Series` holds a single dimension of data.  Think of it as a single column, similar to a plain `list` in Python. But there are some key features that Pandas offers.

In [3]:
# declare a Series of temperatures
my_series = pd.Series([97.5, 98.2, 99.5, 98.1, 98.7], name='temperatures')

# print the series
my_series

0    97.5
1    98.2
2    99.5
3    98.1
4    98.7
Name: temperatures, dtype: float64

Note how we called the `Series()` construct in Pandas, and passed a Python list of floating point values to it.  We gave it a name "temperatures."  When we print the series, we see not just the data but also the name provided and the inferred data type (`float54`, which is 64-bit floating point values).  This shows we can store useful metadata with our list of values.

But notice how there ar two columns, not just one, in our series.  The second column is the **index**

In [7]:
# declare a Series of temperatures with a defined index

my_series = pd.Series(
    index = ['MON', 'TUES', 'WED', 'THURS', 'FRI'],
    data = [97.5, 98.2, 99.5, 98.1, 98.7],
    name = 'temperatures')

# pring the series
my_series

MON      97.5
TUES     98.2
WED      99.5
THURS    98.1
FRI      98.7
Name: temperatures, dtype: float64

In [8]:
# print the wed element

my_series['WED']

np.float64(99.5)

We aso call index the **axis**, and we call each element **axis labels** (e.g. consecutive integers or MON, TUE, WED...).  We call the actual data the **values** in the series.  The values do not have to be numeric.  They can be strings, dates, or any arbitrary Python type.  It is ideal a given series has the same datatype throughout its values for efficiency, and therefore can leverage fast vectorized operations behind the scenes.

## DataFrames
Whereas a series holds a single column of data, a **dataframe** in Pandas holds multiple columns of data.  It is also the data structure you will work with the most in Python.

In [11]:
df = pd.DataFrame(data=[
    ('Otter Antiques', '5732 Serenity Ln', 'Addison', 'TX', 75031, 'COMMERCIAL', 55),
    ('North Exa Energy', '67 Hearst Dr', 'Plano', 'TX', 75093, 'INDUSTRIAL', 73),
    ('City of Plano', '239 Plano Dr', 'Plano', 'TX', 75093, 'GOVERNMENT', 193),
    ],
    columns=['COMPANY_NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'CATEGORY', 'NUM_EMPLOYEES']
)

# print df
df

,COMPANY_NAME,ADDRESS,CITY,STATE,ZIP,CATEGORY,NUM_EMPLOYEES
0,Otter Antiques,5732 Serenity Ln,Addison,TX,75031,COMMERCIAL,55
1,North Exa Energy,67 Hearst Dr,Plano,TX,75093,INDUSTRIAL,73
2,City of Plano,239 Plano Dr,Plano,TX,75093,GOVERNMENT,193

We can initialize thes three recods by assigning a collection containing collections to the `data` paramet, where each sub-collection is a row of data.  In this case I create a list of tuples.  The names of each column are provided as a list of strings to the `columns` parament.  Notice there are seven colunns and three rows.  We can obtain thes dimensions using the dataframe's `shape` property.

In [12]:
df.shape

(3, 7)

In [13]:
df['ADDRESS']

0    5732 Serenity Ln
1        67 Hearst Dr
2        239 Plano Dr
Name: ADDRESS, dtype: str

In [16]:
# NOTE:  for multiple columns, a double bracket must be used
df[['ADDRESS', 'COMPANY_NAME']]

            ADDRESS      COMPANY_NAME
0  5732 Serenity Ln    Otter Antiques
1      67 Hearst Dr  North Exa Energy
2      239 Plano Dr     City of Plano

In [17]:
df.columns

Index(['COMPANY_NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'CATEGORY',
       'NUM_EMPLOYEES'],
      dtype='str')

In [18]:
df.index

RangeIndex(start=0, stop=3, step=1)

Note the index implementation returned is a `RangeIndex` which is a simple integer index defined by a range and step (typically `1` for a simple consecutive integer).  To retrieve an index by row, use the `loc[]` getter with the row number.

In [21]:
df.loc[2]

COMPANY_NAME     City of Plano
ADDRESS           239 Plano Dr
CITY                     Plano
STATE                       TX
ZIP                      75093
CATEGORY            GOVERNMENT
NUM_EMPLOYEES              193
Name: 2, dtype: object

You can manipulate and change the row index, most commonly by using the `set_index()` function and specifying which column you want as the index.  Below we set the 'CATEGORY' column to become the index.  Note we set `inplace` to be true so it edits the existing datagrame rather than create a new one.

In [25]:
df.set_index('CATEGORY', inplace=True)

You can use the `loc[]` getter to look up a record by the company name

In [26]:
df.loc['COMMERCIAL']

ADDRESS          5732 Serenity Ln
CITY                      Addison
STATE                          TX
ZIP                         75031
NUM_EMPLOYEES                  55
Name: COMMERCIAL, dtype: object

If you study the `index` property now, notice it is no longer a `RangeIndex` but rather a plain `Index` organized by string objects.

In [27]:
df.index

Index(['COMMERCIAL', 'INDUSTRIAL', 'GOVERNMENT'], dtype='str', name='CATEGORY')

To reset the index back to the default, call `reset_index()`. Use the `inplace`modifier so it edits the existing dataframe rather than create a new one.

In [28]:
df.reset_index(inplace=True)

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)